FROM python:3.11-slim

WORKDIR /app

COPY ./src /app/src
COPY pyproject.toml /app/

RUN pip install poetry
RUN poetry config virtualenvs.create false && poetry install --no-root --no-dev

CMD ["poetry", "run", "uvicorn", "src.mcp_server.main:app", "--host", "0.0.0.0", "--port", "8000"]